=== facebook/openbmc/common/recipes-core/rackmon2/rackmon/schemas/RegisterMapConfigSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "regmap",
  "title": "Rackmon Register Map Configuration",
  "description": "Schema to test the Register Map JSON configuration",
  "type": "object",
  "required": ["name", "address_range", "probe_register", "baudrate", "registers"],
  "additionalProperties": false,
  
  "properties": {
    "name": {
      "type": "string"
    },
    "address_range": {
      "type": "array",
      "minItems": 1,
      "maxItems": 256,
      "items": {
        "type": "array",
        "minItems": 2,
        "maxItems": 2,
        "items": {
          "type": "integer",
          "minimum": 0,
          "maximum": 255
        }
      }
    },
    "probe_register": {
      "type": "integer",
      "minimum": 0,
      "maximum": 65535
    },
    "time_sync": {
      "type": "object",
      "required": ["address"],
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "integer",
          "minimum": 0,
          "maximum": 65535
        },
        "interval": {
          "type": "integer",
          "minimum": 0
        }
      }
    },
    "baudrate": {
      "type": "integer",
      "minimum": 19200,
      "maximum": 115200
    },
    "max_span_length": {
      "type": "integer",
      "minimum": 1,
      "maximum": 120
    },
    "parity": {
      "type": "string",
      "enum": ["EVEN", "ODD", "NONE"]
    },
    "registers": {
      "type": "array",
      "minItems": 1,
      "maxItems": 65536,
      "items": {
        "$ref": "registermap/register.json#/definitions"
      }
    }
  }
}

=== facebook/openbmc/common/recipes-core/rackmon2/rackmon/configs/register_map/orv2_psu.json
{
    "name": "ORV2_PSU",
    "address_range": [
        [
            160,
            191
        ]
    ],
    "probe_register": 104,
    "baudrate": 19200,
    "time_sync": {
        "address": 298,
        "interval": 3600
    },
    "max_span_length": 16,
    "registers": [
        {
            "begin": 0,
            "length": 8,
            "format": "STRING",
            "name": "PSU MFR MODEL"
        },
        {
            "begin": 16,
            "length": 8,
            "format": "STRING",
            "name": "PSU MFR DATE"
        },
        {
            "begin": 32,
            "length": 8,
            "format": "STRING",
            "name": "PSU FB Part #"
        },
        {
            "begin": 48,
            "length": 4,
            "format": "STRING",
            "name": "PSU HW Revision"
        },
        {
            "begin": 56,
            "length": 4,
            "format": "STRING",
            "name": "PSU FW Revision"
        },
        {
            "begin": 64,
            "length": 16,
            "format": "STRING",
            "name": "PSU MFR Serial #"
        },
        {
            "begin": 96,
            "length": 4,
            "format": "STRING",
            "name": "PSU Workorder #"
        },
        {
            "begin": 104,
            "length": 1,
            "keep": 10,
            "changes_only": true,
            "format": "FLAGS",
            "flags": [
                [
                    13,
                    "Forced Backup"
                ],
                [
                    11,
                    "Power Fail signal"
                ],
                [
                    10,
                    "Redundancy Lost"
                ],
                [
                    9,
                    "PSU Not Responding"
                ],
                [
                    8,
                    "SoH Discharge"
                ],
                [
                    7,
                    "SoH Requested"
                ],
                [
                    6,
                    "Battery Alarm"
                ],
                [
                    5,
                    "Fan Alarm"
                ],
                [
                    4,
                    "Temp Alarm"
                ],
                [
                    3,
                    "Current Feed (Boost Converter) Failed"
                ],
                [
                    2,
                    "Battery Charger Failed"
                ],
                [
                    1,
                    "Aux 54V Converter failed"
                ],
                [
                    0,
                    "Main Converter Failed"
                ]
            ],
            "name": "PSU Status"
        },
        {
            "begin": 105,
            "length": 1,
            "keep": 10,
            "changes_only": true,
            "format": "FLAGS",
            "flags": [
                [
                    15,
                    "Unknown Error"
                ],
                [
                    14,
                    "Bad Size"
                ],
                [
                    13,
                    "Overflow/Underflow"
                ],
                [
                    12,
                    "Access Denied"
                ],
                [
                    11,
                    "Unsupported Command"
                ],
                [
                    9,
                    "Busy"
                ],
                [
                    8,
                    "Normal"
                ],
                [
                    7,
                    "BBU Charge_Enable_L signal mismatch"
                ],
                [
                    6,
                    "BBU Stop_Discharge_L signal mismatch"
                ],
                [
                    2,
                    "End of Life"
                ],
                [
                    1,
                    "Low Voltage"
                ],
                [
                    0,
                    "BBU Fail"
                ]
            ],
            "name": "BBU Status (0x00 of the BBU)"
        },
        {
            "begin": 107,
            "length": 1,
            "keep": 10,
            "changes_only": true,
            "format": "FLAGS",
            "flags": [
                [
                    15,
                    "Capacity Mode"
                ],
                [
                    14,
                    "Charger Mode"
                ],
                [
                    13,
                    "Alarm Mode"
                ],
                [
                    9,
                    "Primary Battery"
                ],
                [
                    8,
                    "Charge Controller Enabled"
                ],
                [
                    7,
                    "Battery OK Flag"
                ],
                [
                    1,
                    "Primary Battery Support"
                ],
                [
                    0,
                    "Internal Charge Controller"
                ]
            ],
            "name": "BBU Battery Mode (0x03 of BBU)"
        },
        {
            "begin": 108,
            "length": 1,
            "keep": 10,
            "changes_only": true,
            "format": "FLAGS",
            "flags": [
                [
                    15,
                    "Over Charged Alarm"
                ],
                [
                    14,
                    "Terminated Charge Alarm"
                ],
                [
                    12,
                    "Over Temp Alarm"
                ],
                [
                    11,
                    "Terminate Discharge Alarm"
                ],
                [
                    9,
                    "Remaining Capacity Alarm"
                ],
                [
                    8,
                    "Remaining Time Alarm"
                ],
                [
                    7,
                    "Initialized"
                ],
                [
                    6,
                    "Discharging"
                ],
                [
                    5,
                    "Fully Charged"
                ],
                [
                    4,
                    "Fully Discharged"
                ]
            ],
            "name": "BBU Battery Status (0x16 of BBU)"
        },
        {
            "begin": 109,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 1 (0x80 of the BBU)"
        },
        {
            "begin": 110,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 2 (0x81 of the BBU)"
        },
        {
            "begin": 111,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 3 (0x82 of the BBU)"
        },
        {
            "begin": 112,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 4 (0x83 of the BBU)"
        },
        {
            "begin": 113,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 5 (0x84 of the BBU)"
        },
        {
            "begin": 114,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 6 (0x85 of the BBU)"
        },
        {
            "begin": 115,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 7 (0x86 of the BBU)"
        },
        {
            "begin": 116,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 8 (0x87 of the BBU)"
        },
        {
            "begin": 117,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 9 (0x88 of the BBU)"
        },
        {
            "begin": 118,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 10 (0x89 of the BBU)"
        },
        {
            "begin": 119,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 11 (0x8A of the BBU)"
        },
        {
            "begin": 120,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 12 (0x8B of the BBU)"
        },
        {
            "begin": 121,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Cell Voltage 13 (0x8C of the BBU)"
        },
        {
            "begin": 122,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Temp 1 (0x90 of the BBU)"
        },
        {
            "begin": 123,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Temp 2 (0x91 of the BBU)"
        },
        {
            "begin": 124,
            "length": 1,
            "keep": 10,
            "format": "INTEGER",
            "endian": "L",
            "name": "BBU Temp 3 (0x92 of the BBU)"
        },
        {
